### ISSUE TITLE
Icons for "Move left, Move right, Remove character", replaced by unicode strings

### ISSUE THREAD

**Issue by nswarup14** [sugarlabs/calculate-activity#65]
Attached screenshot below which shows the problem
![calculate](https://user-images.githubusercontent.com/34597895/60401049-af9b4180-9b99-11e9-8cf4-de3870630dee.png)

Rather than displaying the icons, unicode strings such as "\u2190 ,\u2192" are displayed.

Checked the between https://github.com/sugarlabs/calculate-activity/commit/d21e9108260219d3aef2a01866d35e5044587dd9 and https://github.com/sugarlabs/calculate-activity/commit/58b898949b760769bb87246f53b865be9fde7d85. The issue is introduced in the latter commit.

**Comment by quozl** [comment]
Thanks.  I've reproduced, and reverted 58b898949b760769bb87246f53b865be9fde7d85.

**Comment by nswarup14** [comment]
@quozl 
Thanks. Closing the issue

**Comment by quozl** [comment]
Why?  Issue still exists, if the Port to Python 3 source code is used.  All I've done by reverting is remove the issue from the _master_ branch.  We still need the source code ported to Python 3.

**Comment by Aniket21mathur** [comment]
Thanks. Reproduced. Did some work around.
* The issue does not happen to me on running the activity with Python 3 version of the toolkit.
* The issue takes place only when we run the Python 3 Ported activity with Python 2 version of the toolkit. Which I don't think is the right practice.

To avoid such confusion(at least after the Port to python 3 commit is merged), I think we should do any further changes compatible with Python 3 and test those with Python 3 version of the toolkit. But since we don't have Python 3 packages yet, we can't scale, so we should wait to have packages before merging "Port to Python 3" to master.

@quozl @nswarup14 What do you suggest?

**Comment by Aniket21mathur** [comment]
> Checked the between [d21e910](https://github.com/sugarlabs/calculate-activity/commit/d21e9108260219d3aef2a01866d35e5044587dd9) and [58b8989](https://github.com/sugarlabs/calculate-activity/commit/58b898949b760769bb87246f53b865be9fde7d85). The issue is introduced in the latter commit.

@nswarup14 I am still confused how you hited this issue. Please help.

**Comment by quozl** [comment]
Thanks for diagnosing.  It reminds me again how I should not test activities using `sugar-activity`.

**Comment by Aniket21mathur** [comment]
> Thanks for diagnosing. It reminds me again how I should not test activities using `sugar-activity`.

I am confused, did I did anything wrong ? :sweat_smile:

**Comment by quozl** [comment]
Can you think of a way to detect and warn when an activity is run in Python 2 when it has already been ported to Python 3?  :grin:

**Comment by Aniket21mathur** [comment]
I think we already have it, please see https://github.com/sugarlabs/sugar-toolkit-gtk3/commit/aa8a5e70c415e6c2acf4ff373d9b366ac4692bb1#diff-35db2ad94d2c22d773bce7bb50fdacafR131.

If we have in mind that we are testing for Python 3 activity, and we still get this warning, means something is wrong :grin: 

We can edit the warning, adding "or you might be using the wrong toolkit version" or something like that :sweat_smile: .

**Comment by quozl** [comment]
We don't have in mind that we are testing a Python 3 activity.  As far as I know, only you and I can do that at the moment, using hand crafted configurations.

**Comment by Aniket21mathur** [comment]
> We don't have in mind that we are testing a Python 3 activity. As far as I know, only you and I can do that at the moment, using hand crafted configurations.

Thanks, Agreed.

I have something in mind, like somehow reading the Python version from the environment and then comparing it with the command line input, `sugar-activity .` or `sugar-activity3 .`. 

I will try that and let you know :-)

**Comment by pro-panda** [comment]
Check if `exec` in `activity/activity.info` is consistent with the command being used to run the activity. Raise a warning otherwise

**Comment by quozl** [comment]
I've tried cherry-picking 58b898949b760769bb87246f53b865be9fde7d85 and resolving a conflict, but something between then and now has broken it; calculations display no result, and logs contain;

```log
Traceback (most recent call last):
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 859, in keypress_cb
    return f(self)
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 309, in <lambda>
    'Return': lambda o: o.process(),
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 517, in process
    s = numParser.standard(s)
  File "/usr/share/sugar/activities/Calculate.activity/numParser.py", line 41, in standard
    localString = localString.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```

```python
    def process(self):
        """Parse the equation entered and show the result."""

        s = str(self.text_entry.get_text())
        s = numParser.standard(s)
        label = str(self.label_entry.get_text())
```

So it seems the new numParser requires unicode data type?  Anyone have any ideas?

**Comment by Saumya-Mishra9129** [comment]
@quozl The issue is fixed. We forgot to close this.
